var words = [
    "square",
    "circle",
    "bowl",
    "thunderstorm",
    "trapezoid",
    "triangle",
    "tree",
    "worm",
    "snake",
    "field",
    "mountain",
    "human",
    "watermelon",
    "germany",
    "united states",
    "france",
    "italy",
    "ireland",
    "mexico",
    "canada",
    "newspaper",
    "table",
    "car",
    "window",
    "house",
    "banana",
    "sun",
    "moon"
];
export default words;